### ISSUE TITLE
Disable changing email login ID via configuration

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1130]
In some application, the email address is used to organize people. For example, the employee from Company A must use an email address ending with `@company-a.com`. Letting people to change it to arbitrary email or even an email domain of Company B will break some invariants the application wants to hold.

**Comment by louischan-oursky** [comment]
Some random thoughts

```yaml
identity:
  login_id:
    keys:
    - key: email
      type: email
      removable: true
      updatable: true
  oauth:
    providers:
    - alias: google
      type: google
      removable: true
```
