### ISSUE TITLE
Create options to mark if each OAuth identity meant verified or not

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#178]
## Intended Usage

For most OAuth identity, say Gmail login, usually we could treat the gmail email address as verified.

However, it is possible that some services might want to verify the email address even if the email address was provided by 3rd parties login, or it is possible that some OAuth login is trustworthy while some are not...

So we need an option to mark:

- If each OAuth Provider's email address / phone no. provided is automatically mark as verified or not
- If not, and if the user is required to be verified, our Auth UI will try to verify it during the sign up process after SSO login.

I guess the option can be someting like `oauth.providers.trust_email_as_verified` or `oauth.providers.trust_phone_as_verified`

## Questions

From #172 , @kiootic asked the following questions, and here are Ben's initial comments:

* Can the user verify an OAuth identity?
    * I think user can verify the identity in the sense that, say if Google login is marked as not trusted, and verification is required, the email address will go through verification process.
* If there are OAuth identity & login ID identity with same email, would verifying one of them makes all of them verified?
    * I think it is okay for the use case.
* If user unlinked an OAuth identity, would the login ID identity with same email become unverified?
    * If it still have another OAuth with the same emaill address, it is ok, if not then it is not verified.

**Comment by louischan-oursky** [comment]
I agree with Ben's comments above.

My proposed configuration

```yaml
identity:
  oauth:
    providers:
    - type: google
      alias: google
      client_id: client_id
      verification:
        # The default is true, same as login ID.
        enabled: true
        # The default is true, same as login ID.
        required: true
        # Valid values are just "email" and "phone_number"
        # https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
        # If the developer does not want the email claim of Google being considered as verified,
        # set this field to an empty list.
        # The default value of this field depends on type
        # For type like google, facebook, apple, the default is ["email"]
        # Otherwise the default is an empty list.
        assumed_verified_claims: ["email", "phone_number"]

```
