### ISSUE TITLE
Make claims verifiable

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#198]
Currently, the minimum unit of verification is identity. However, an identity may have both email & phone number, and we want to verify them separately. We should instead make claim the unit of verification.

Logic changes:
- Add `verified_claims` property (`Set<Claim>; Claim { name: string, value: string }`) to user entity:
    - maybe normalized as `_auth_verified_claims`, or JSONB in user row
- Add verified claim to user in verification process & add OOB authenticator process
    - do not add authenticator in verification process
- For now, assume every identity may have either email or phone number, never both

Config changes:
```yaml
# remove verification config in login ID key config
verification:
    # criteria, code_expiry_seconds, etc.
    claims:
        email:
            enabled: true
            required: true
        phone_number:
            enabled: true
            required: true
````

**Comment by louischan-oursky** [comment]
[Ben's comment](https://github.com/authgear/authgear-server/pull/202#issuecomment-681967774)

> @kiootic @louischan-oursky thanks for the update, I understand the reason behind it.
> 
> But I’m a bit puzzled by the change of specification and configuration.
> 
> Comment for readability of the specification:
> 
> It is not clear and hard to reason the configuration -- there are no claims for user but only for each identity (which is Login ID / OAuth Provider), I think it need to be explained in the spec for readability of future developer.
> Some questions / problems as follows:
> 
> The logic of user doesn't have claims, while each identity has claims, make the configuration hard to guess / make sense. It should be verification.[identity].claims instead of verification.claims
> The problem of 1 also make it impossible to handle the following use cases:
> 2.1. What if I want to trust Google’s email but not Wechat’s email? And both return the claims called email?
> 2.2. What if I want to have multiple login ID with email type, and only the 1st one require verification?
> Just to be sure, so if a OIDC provider return a claim called phone instead of phone_number, it will be verification.claims.phone?

**Comment by louischan-oursky** [comment]
> It is not clear and hard to reason the configuration -- there are no claims for user but only for each identity (which is Login ID / OAuth Provider), I think it need to be explained in the spec for readability of future developer.

The Identity Claims is specified in `/docs/specs/user-model.md#identity-claims`, while the User Claims (ID Token) is specified in `/docs/specs/oidc.md#id-token`. I suggest we specify the User Claims in `/docs/specs/user-model.md` and the ID Token session just reference to it.

We should also clarify that there is no `email` claim in the User Claims at the moment, since we do not have primary identity.

> What if I want to trust Google’s email but not Wechat’s email? And both return the claims called email?
> What if I want to have multiple login ID with email type, and only the 1st one require verification?

Sorry it was an oversight when we made the change. We want make the minimum unit of verification is a claim, but still maintain the above functionality.

Therefore, I suggest the new configuration is applied to both Login ID Identity and OAuth Identity. Here is an example.

```yaml
identity:
  login_id:
    keys:
    - key: email
      type: email
      verification:
        claims:
          email:
            # There is no trusted field here!
            enabled: true
            required: true
          # Technically, you can add phone_number here,
          # But it does not have any effect.
          # This is because a Email Login ID Identity never produce a `phone_number` claim.
    - key: phone
      type: phone
      verification:
        claims:
          phone_number:
            enabled: true
            required: true
  oauth:
    providers:
    - alias: google
      type: google
      client_id: "the_client_id"
      verification:
        claims:
          email:
            trusted: true
            enabled: true
            required: true
         # Technically, you can add phone_number here,
         # But it does not have any effect.
         # This is because Google is known that it never returns a `phone_number` claim.
```

The minimum unit of verification is still a claim. When a claim was verified, we only store this fact.
The verification status of an identity is then derived from the configuration and the verified claims the user has.

The configuration is as follows:

```yaml
identity:
  login_id:
    keys:
    - key: email
      type: email
      verification:
        claims:
          email:
            enabled: true
            required: true
  oauth:
    providers:
    - alias: google
      type: google
      client_id: "the_client_id"
      verification:
        claims:
          email:
            trusted: true
            enabled: true
            required: true
```

The user first signs up with their Google account `user@gmail.com`.
Since `trusted` is true, we skip the verification step and mark the claim as verified.

```json
[
  { "email": "user@gmail.com" }
]
```

Later on the user add Email Login ID Identity of `user@gmail.com`.
The verification step is skipped and the newly added identity is considered as verified.

> Just to be sure, so if a OIDC provider return a claim called phone instead of phone_number, it will be verification.claims.phone?

We now only support selected OAuth provider so we can normalize the claim names if the provider is known for violating the OIDC specification. In the future, if we support a generic OIDC provider, we expect it to be conformant. So `phone` is just an unrecognized claim, we simply ignore it.

**Comment by chpapa** [comment]
> I suggest we specify the User Claims in /docs/specs/user-model.md and the ID Token session just reference to it.

Sure this will be good. It is more just for readability

> We should also clarify that there is no email claim in the User Claims at the moment, since we do not have primary identity.

Aware of it, yea I think it is good to mention it too. But I'm also worried we will need to figure it out sooner or later...

> Therefore, I suggest the new configuration is applied to both Login ID Identity and OAuth Identity. Here is an example.

I think the example is good, and is extensible... (in future, maybe we need to support some OIDC provider which will supply a claim like `email_verified` -- but we don't need it now as long as the configuration now is logically consistent and extensible)

> In the future, if we support a generic OIDC provider, we expect it to be conformant. So phone is just an unrecognized claim, we simply ignore it.

@louischan-oursky may you explain more what does this meant?

**Comment by louischan-oursky** [comment]
I mean if we support a generic OIDC provider in the future, we expect it to return claims according to [the spec](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims). That is the email should be specified in the `email` claim and the phone number should be specified in the `phone_number` claim. If the provider returns the phone number in the `phone` claim or anything else, it is just an unrecognized claim and simply be ignored.

For more background information, right now we supports Google, Apple, Azure AD, Facebook and LinkedIn. Google, Apple and Azure AD  are OIDC providers but Apple is not very conformant to the spec. We need to handle it specially. Facebook and LinkedIn are just OAuth 2.0 providers, so their integration is specific.

**Comment by kiootic** [comment]
For your reference: Keycloak has a concept called [mappers](https://www.keycloak.org/docs/latest/server_admin/#_protocol-mappers), it allows developer to map provider claims to Keycloak claims.

**Comment by kiootic** [comment]
To summarize the discussion, @chpapa raised two suggestions:
1. Support having two login ID keys with same type, but different verification configuration
2. Support configuring trusted claims from SSO providers.

With reference to #221 , suggestion 1 is no longer relevant.

I'd propose this update to the existing configuration to address suggestion 2:
```yaml
identity:
  oauth:
    providers:
    - alias: google
      type: google
      client_id: "the_client_id"
      claims:
        email:
          trusted: true # Indicates whether the claim is trusted (i.e. verified)

verification:
  # These are existing configs
  claims:
    email:
      enabled: true
      required: true
    phone_number:
      enabled: true
      required: true
  # Previously, criteria derives user verification status using identity verification status.
  # It will use claim verification status instead.
  criteria: any
```

To support recognizing non-standard claims from SSO providers (e.g. `phone` instead of `phone_number`), we can support claim mappings in future. For example, supporting a configuration of `identity.oauth.providers[].claims.phone.mapped_to: "phone_number"`, so Authgear can map the provider claims automatically.

**Comment by chpapa** [comment]
> For your reference: Keycloak has a concept called mappers, it allows developer to map provider claims to Keycloak claims.

@kiootic thx, interesting concept.

> I'd propose this update to the existing configuration to address suggestion 2:

Well, from readability / understandability-wise, I think the configuration should looks like this:

```yaml
identity:
  login_id:
    keys:
    - key: email
      type: email
      verification:
          enabled: true
          required: true
          # There is no trusted field here!
    - key: phone
      type: phone
      verification:
          enabled: true
          required: true
  oauth:
    providers:
    - alias: google
      type: google
      client_id: "the_client_id"
      verification:
        claims:
          email:
            reverify_enabled: true
            reverify_required: true
            # actuallly is it a good practices to have enum in yaml? 
            # like identity.oauth.providers.verification.claims.email: [trusted, optional, required]
```

Reasons are:
- For login ID, It is not intuitive to think login_id have a "claims", and email's verification must be email address, so do phone.
- The combination of `trusted` + `enabled` + `required` is quite complicated to imagine / understand, simplify it to two boolean, or even an enum like [trusted, optional, required]?

**Comment by kiootic** [comment]
I suppose I'm not being clear enough with my proposal, I mean:
- The login ID configuration remains as-is, i.e. no verification configuration in there. The verification configuration used is inferred based on the corresponding claim of login ID.
- Verification configuration for claims is lift to a top-level config, as described.
- The claim configuration in OAuth providers contains only the 'trusted' flag; its verification configuration would still be based on the claim verification configuration at top-level.
- The trust flag may be used for various purpose, not limiting to verification of claim. For example:
    - If the same email exists during signup, we may offer auto-merge of identities if the email claim is trusted.
    - We may ignore the email when checking for uniqueness of email during signup if the email claim is untrusted.

Personally, I'd like to avoid introducing different verification behavior based on which identity the claim comes from.

**Comment by chpapa** [comment]
@kiootic 

Ummm, but I think your proposal is a bit hard to understand for newcomers, they need to understand why identity have claims, and aware that to change the verification requirement of their email LoginID meant changing the `verification.claims.email`, I didn't get it when I first look at it last week neither, and only understood later. (And hence suggested the clarification in the spec, but we can't do the same for other developer users)

> Personally, I'd like to avoid introducing different verification behaviour based on which identity the claim comes from.

I think the requirement of different OAuth provider's email address is trusted or not, already made us have different verification behaviour based on which identity the claim comes from? 

And btw, what about the idea of using `email: [trusted, optional, required]` instead of a combination of 2 / 3 booleans for different behaviour?

**Comment by louischan-oursky** [comment]
> And btw, what about the idea of using email: [trusted, optional, required] instead of a combination of 2 / 3 booleans for different behaviour?

Good suggestion.

**Comment by kiootic** [comment]
> Ummm, but I think your proposal is a bit hard to understand for newcomers, they need to understand why a login ID identity have claims, and aware that to change the verification requirement of their email LoginID meant changing the verification.claims.email, I didn't get it when I first look at it last week neither, and only understood later. (And hence suggested the clarification in the spec, but we can't do the same for other developer users)

The concept of 'identity claim' is rather central in the user model. In fact, the admin API exposes them directly, so I expect developer to at least know about them, and we should mention them as introductory concepts in documentation.

Also, we can't expect every developers to understand every pieces of configuration at a glance. I remembered we had similar conversation before, but my view is that developer should know to consult documentation if they do not understand how to perform the intended task.

> However, I don't think we have to design for such a crazy case.... but I'm also not 100% sure there is other "more normal case" might need these kinds of configuration.

As you mentioned, this is a very edge case. I don't think we should design for such case at this stage. I'm also not 100% sure that such 'more normal cases' exist, and supporting this may unnecessarily increase the complexity of design.

My observation is that recently, much of the time spent on design is not on the feature itself, but rather the interaction between features (e.g. OAuth and verification, MFA and password-less login).

Considering verification and identity as individual features, as I proposed, their interaction is straight-forward: identity may set verified claims according to trust configuration, or request verification for a claim, while verification can act independently.

However, if the verification status of a claim also depends on the origin identity, it complicates the interaction and may led to further problems:
- does this mean verification process need not only the email, but which identity the email comes from?
- if one identity requires email verification, another has optional email verification, and both have same email, is verification required or optional?

I'm not sure if it offers real benefits to developer, or would lead to feature bloats/unforeseen interactions.

> And btw, what about the idea of using email: [trusted, optional, required] instead of a combination of 2 / 3 booleans for different behaviour?

I agree on combining optional/required as a enum. However, as mentioned before in comment, the trust flag may be used for purposes other than verification, so I don't think it should be grouped in verification configuration.

**Comment by chpapa** [comment]
> Also, we can't expect every developers to understand every pieces of configuration at a glance. I remembered we had similar conversation before, but my view is that developer should know to consult documentation if they do not understand how to perform the intended task.

I understood your point, but if we can simplify things without making people refer to documentation all the time, and also perform the intended task, it is even better. It is just like why we emphasis good naming in modern software engineering -- yea we can use some weird name / concept but it is better if people don't have to lookup documentation all the times.

> I'm not sure if it offers real benefits to developer, or would lead to feature bloats/unforeseen interactions.

So i think this is the problem we are facing now, we don't know the chance of having to revert it back and make breaking changes on configuration (and even worse, the whole concept of what we are verifying) vs the benefits of having the flexibility.

And because you have been so emphasis of avoiding breaking changes, I'm quite uncertain on what are the implications of introducing claims here...

I think we should list out the pros and cons below?

> However, as mentioned before in comment, the trust flag may be used for purposes other than verification, so I don't think it should be grouped in verification configuration.

We have to be very careful on this side effect, not to surprise people (and blame them not reading documentation again lol)

## Pros and Cons of having verification configuration on each identity

Let's list out here to help us make better judgement call?

### Pros of verification on each identity
* Avoid future breaking changes on the claims concept and configuration format
* Support cases that email/phone from some OAuth Provider is not trusted nor need to verify, while others are trusted or verified.

### Cons of verification on each identity
* Need to handle the cases of if multiple identity have the same email/phone, to verifying one automatically verify the others?
* @kiootic can you help copy this when u comment on it and add more?

**Comment by chpapa** [comment]
BTW, I'm also 50/50 on this, so more thoughts are welcome.

**Comment by chpapa** [comment]
@kiootic let's keep it simple since I don't have a good use case and finger cross...

However, I would like to propose the following changes:

* `identity.oauth.providers[].claims.email.trusted` renamed to `is_verified` (or any other idea?), since we seem had a lot of miscommunication on the meaning of `trust`.
* Shall we rename `verifications.claims` to `claims_verification` (as illustrated below)? 
* Shall we implement the `identity.oauth.providers[].claims.[claim name].mapped_to` at one go? 
* Any idea how we can tell new comer login_id will become claims?

And since we decided to remove `key` in the configuration before, may I confirm the following would be the new configuration? @kiootic @louischan-oursky 

```
identity:
  login_id:
    - type: phone
  oauth:
    providers:
    - alias: google
      type: google
      client_id: "the_client_id"
      claims:
        email:
          is_verified: true # Indicates whether the claim is trusted (i.e. verified)

claims_verification: # is it better if we change it to `claims_verification` instead of `verification.claims`?
  email:
    enabled: true
    required: true
  phone_number:
    enabled: true
    required: true
  criteria: any
```

**Comment by kiootic** [comment]
> identity.oauth.providers[].claims.email.trusted renamed to is_verified (or any other idea?), since we seem had a lot of miscommunication on the meaning of trust.

I think that's fine.

> Shall we rename verifications.claims to claims_verification (as illustrated below)?

We already have existing configuration in the top-level `verification` key (e.g. verification code expiry), I prefer to keep it nested as `verification.claims`.

> Shall we implement the identity.oauth.providers[].claims.[claim name].mapped_to at one go?

I'm not sure if just a simple key-to-key translation is enough. Some may want Regex pattern matching, value transformation, or even arbitrary mapper function. Do you need it for some use case?

> Any idea how we can tell new comer login_id will become claims?

I suppose we should introduce the user model (i.e. user, identity, authenticator) as basic concepts in documentation. Then, identity claims would be introduced there.

**Comment by louischan-oursky** [comment]
> identity.oauth.providers[].claims.email.trusted renamed to is_verified (or any other idea?), since we seem had a lot of miscommunication on the meaning of trust.

`assume_verified` is even more verbose IMO.

> Shall we implement the identity.oauth.providers[].claims.[claim name].mapped_to at one go?

As mentioned by Terry, this claims mapping feature could involve many interesting functions. I prefer we do not implement it now.

**Comment by chpapa** [comment]
> As mentioned by Terry, this claims mapping feature could involve many interesting functions. I prefer we do not implement it now.

Agree, ok

> assume_verified is even more verbose IMO.

I thought of it too, but feel too long, but if you guys think it is easier to understand, let's go for it.

> We already have existing configuration in the top-level verification key (e.g. verification code expiry), I prefer to keep it nested as verification.claims.

ok

**Comment by chpapa** [comment]
So just to confirm the final configuration is something like this:

```yaml
identity:
  login_id:
    - type: phone
  oauth:
    providers:
    - alias: google
      type: google
      client_id: "the_client_id"
      claims:
        email:
          assume_verified: true # Indicates whether the claim is trusted (i.e. verified)

verification:
  claims:
    email:
      enabled: true
      required: true
    phone_number:
      enabled: true
      required: true
  criteria: any
```
