### ISSUE TITLE
Make Passkey on by default

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2303]
When creating a new project, default turn on passkey to promote the use of it.
The design and copy in the wizard need to be changed:

**Changes**
[WIP...]

**Comment by louischan-oursky** [comment]
If we want to make passkey turned on by default in the config file, I need to make a migration to clear the explicit default value in the config of existing app.

Given a config of a particular app

```yaml
authentication:
  identities: ["oauth", "login_id"]
  primary_authenticators: ["password"]
```

We need to clear the defaults so that it becomes

```yaml
authentication: {}
```

Then at runtime the config will pick up the new defaults

```yaml
authentication:
  identities: ["oauth", "login_id", "passkey"]
  primary_authenticators: ["password", "passkey"]
```

However, this approach will not work if `primary_authenticators` has been modified. For example, an app may have `primary_authenticators: ["oob_otp_email"]` due to going through the onboarding wizard.
