### ISSUE TITLE
The identities list is cleared when changing the primary authenticator in portal

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#2308]
**Describe the bug**
Don't have the steps to reproduce the problem yet, this happens during the ux test. When user updates the primary authenticator list in portal, it changes the config and the identities list becomes an empty array. 

**Authgear Version**
 - Version: staging-2022-08-12.0

**To Reproduce**
Update and save the config in the portal authenticator page when the identities are empty (using default) in the `authgear.yaml`

1. Create a new app
2. Update and save on the portal authenticator page
3. An empty array will be stored in `authgear.yaml`, no identities will be enabled

**authgear.yaml of the app**
```
authentication:
  identities: []
  primary_authenticators:
  - oob_otp_sms
  - password
  secondary_authentication_mode: required
  secondary_authenticators:
  - totp
authenticator:
  oob_otp:
    sms:
      phone_otp_mode: whatsapp
http:
  cookie_domain: ****
  public_origin: ****
id: trial
identity:
  login_id:
    keys:
    - type: email
    - key: phone
      type: phone
oauth:
  clients:
  - access_token_lifetime_seconds: 1800
    client_id: ****
    grant_types:
    - authorization_code
    - refresh_token
    is_first_party: true
    name: My App
    post_logout_redirect_uris:
    - http://localhost:4000/
    redirect_uris:
    - http://localhost:4000/auth-redirect
    refresh_token_idle_timeout_enabled: true
    refresh_token_idle_timeout_seconds: 2592000
    refresh_token_lifetime_seconds: 31449600
    response_types:
    - code
    - none
    x_application_type: spa
verification:
  claims:
    email:
      required: false
```
