### ISSUE TITLE
Incorrect copywriting for primary authenticator alternatives

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#2314]
**Describe the bug**
Incorrect copywriting for primary authenticator alternatives

**Authgear Version**
 - Version: staging-2022-08-12.0

**To Reproduce**
1. Configure the app to have the following settings.
    ```
    authentication:
      primary_authenticators:
      - password
      - oob_otp_email
      ...
    identity:
      login_id:
        keys:
        - key: email
          type: email
    verification:
      claims:
        email:
          enabled: false
          required: false
    ```
1. Signup, input email and click next
2. It shows `Setup email 2-step verification instead`

**Expected behavior**
The copywriting should be something like `Setup passwordless via email instead`.

**Screenshots**
<img width="487" alt="Screenshot 2022-08-15 at 9 35 02 am" src="https://user-images.githubusercontent.com/388892/184604340-a611181d-38b6-4a09-9450-a851fa395fd5.png">
