### ISSUE TITLE
Allow configuration of handling conflicted OAuth and Email Address

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#261]
We should have a new configuration for the user to specify the behaviour when an OAuth Provider's email address clash with Email Address of existing identities.

Such as when user use Google login, to signup/login with an email address that's already verified by another user account

There should be two options:

* Never merge: no matter what, treat the new signup as a separate account
* Merge: it will display a UI at login, to tell users they have already got another account with the same email in this system, ask them to log in again to merge the new OAuth Provider. If `verification.claims.email.required=true`, only email address verified will trigger this merge screen.

Also, we will have an "auto merge" option for each OAuth Provider, if it is set to true, it will automatically merged with the other account if the above option is merge. Again, if `verification.claims.email.required=true`, only email address verified will trigger this merge screen. Something like this:

```yaml
identity:
  oauth:
    providers:
    - alias: google
      type: google
      client_id: "the_client_id"
      claims:
        email:
          auto_merge: true # Will auto trust and merge google's login to existing account. Default is false
```

**Comment by kiootic** [comment]
Discussed with @louischan-oursky :
- When signing up with an identity, the claims of the identity will be used to match existing identity.
   If any identity has same claims, it conflicted and enter the merge flow.
- There are two stage in the merge flow: non-interactive merge/interactive merge.
   Developer can configure to always skip non-interactive merge.
- In non-interactive merge stage, developer can configure to use one of the behaviors:
    - Abort: abort the flow when there is any conflict.
    - AlwaysNew: always create a new account.
    - MergeIfPossible: merge with without user interaction is possible, otherwise go to interactive merge stage.
- Merge with without user interaction is possible if:
    - the conflicted identities have same user; and
    - some of the conflicted identities are verified; and
    - the identity to sign up is verified.
    - This case mainly occurs when user signup with a OAuth identity with a trusted email, and existing login ID/OAuth identity
       has verified email.
- After merging non-interactively, user still need to perform primary/secondary authentication if needed, as in normal authentication flow.
- In interactive merge stage, user is redirected to a page with:
    - information on the identity user attempted to sign up; and
    - inform user that existing account with same claim(email/phone number/username) exists; and
    - Provide options for user to proceed.
- Developer can configure one of the behaviors in interactive merge stage:
    - Merge: request user to authenticate with one of the conflicted identity.
    - AlwaysNew: ask user to confirm creating a new account.
    - MergeOrNew: combination of options in Merge and AlwaysNew
- If user selected merging with one of the conflicted identity:
    - User will need to authenticate with the identity.
    - According to configuration, user will be asked to add the original identity to signup to the existing account, or
       continue without adding the original identity.
    - The merge process is same as logging in as existing identity and adding the identity to signup.

**Comment by chpapa** [comment]
> Abort: abort the flow when there is any conflict.

Does it mean to show an error of existing user in UI?

> the identity to sign up is verified.

This is not necessary if `verification.claims.email.required=false`? (Although that's crazy)

> After merging non-interactively, user still need to perform primary/secondary authentication if needed, as in normal authentication flow.

What does that mean? I suppose the merge itself would mean primary authentication is already done? and only secondary authentication would happen if configured and required?

> This case mainly occurs when user signup with a OAuth identity with a trusted email, and existing login ID/OAuth identity has verified email.

What about if developer user want to do things differently for different OAuth? Say if it is Google Login it could be trusted to auto-merge. If it is from Wechat it can't be trusted and need to proceed with interactive merge. It seems not considered in the flow suggested above.

****

I think the idea is generally okay. Can we have a sample configuration to ensure we are aligned?

**Comment by kiootic** [comment]
> Does it mean to show an error of existing user in UI?

Yes.

> This is not necessary if verification.claims.email.required=false? (Although that's crazy)

`required` flag only determines whether verification is required. If it's false, verification is optional. We require verification to ensure that signing up with arbitrary email login ID cannot take over existing accounts with same email.

> What does that mean? I suppose the merge itself would mean primary authentication is already done? and only secondary authentication would happen if configured and required?

Yes, since this case occurs only for OAuth identities, and OAuth identities skip primary authentication. I wrote it out for clarity, since the stages are still there but just skipped.

> What about if developer user want to do things differently for different OAuth? Say if it is Google Login it could be trusted to auto-merge. If it is from Wechat it can't be trusted and need to proceed with interactive merge. It seems not considered in the flow suggested above.

A trusted email claim from an OAuth provider means the OAuth identity is verified, so non-interactive merge is possible. Otherwise, the identity is not verified, so the condition of non-interactive merge is not fulfilled and interactive merge is required.

**Comment by chpapa** [comment]
> required flag only determines whether verification is required. If it's false, verification is optional. We require verification to ensure that signing up with arbitrary email login ID cannot take over existing accounts with same email.

Sorry I meant `verification.claims.emails.enabled=false`, if verification is disabled, it doesn't make sense to require it?

Or we don't support the whole feature at all if verification is false? 

> A trusted email claim from an OAuth provider means the OAuth identity is verified, so non-interactive merge is possible. Otherwise, the identity is not verified, so the condition of non-interactive merge is not fulfilled and interactive merge is required.

I'm worried this implication is too hard to understand, let's just add another option for it instead of using the criteria of "the identity to sign up is verified." to implicitly meant that? In both configuration file and the Management Portal UI we could have another option to specify this.

**Comment by kiootic** [comment]
> Sorry I meant verification.claims.emails.enabled=false, if verification is disabled, it doesn't make sense to require it?
> Or we don't support the whole feature at all if verification is false?

As mentioned, allowing non-interactive merge with unverified email means easy accounts takeover. Disabled email verification means no email identity is verified, so non-interactive merge is indeed effectively disabled.

> I'm worried this implication is too hard to understand, let's just add another option for it instead of using the criteria of "the identity to sign up is verified." to implicitly meant that? In both configuration file and the Management Portal UI we could have another option to specify this.

So whether auto-merge is possible is configured per OAuth provider. I think that's fine.

**Comment by chpapa** [comment]
> As mentioned, allowing non-interactive merge with unverified email means easy accounts takeover. Disabled email verification means no email identity is verified, so non-interactive merge is indeed effectively disabled.

Actually no, it is not relevant here. I think you misunderstood the case. 

If `verification.claims.emails.enabled=false`, no user in the system have verified their email address. So the ironic part here is every user accounts' email is not verified, while most OAuth Provider would verify it, so when an OAuth Provider user login, it is either "unverified email" take over an account with "unverified email", or "verified email" take over an account with "unverified email"

"Non-interactive merge with unverified email means easy accounts takeover", as mentioned earlier, happens when an OAuth Provider doesn't verify the email address or is compromised. 

****

So come back to the case here, for ease of communication, let me propose the following configuration based on what we have discussed so far first. And then discuss the behaviour to avoid further miscommunication.

(the name `oauth_email_signup_conflict_behaviour` name is temporarily, and I'm also not sure if it should be under `identity`)

```yaml
identity:
  login_id:
  - type: email
  oauth:
    providers:
    - alias: google
      type: google
      client_id: "the_client_id"
      claims:
        email:
          auto_merge: true # Will auto trust and merge google's login to existing account. Default is false

   oauth_email_signup_conflict_behaviour: error # Could be one of the [error, new_account, new_account_with_warning, merge, merge_or_new]
```

* If `identity.oauth_email_signup_conflict_behaviour=error`, it alway show UI: "User already exists, please login"
* If `identity.oauth_email_signup_conflict_behaviour=new_account`, it always continue sign up with a new account
* If `identity.oauth_email_signup_conflict_behaviour=new_account_with_warning`, it always continue sign up with a new account, after user being warned and confirm to sign up a new account in UI
* If `idnetity.oauth_email_signup_conflict_behaviour=merge` and `identity.oauth.providers[].claims.email.auto_merge=true`, then:
  * if the target user's corresponding email claim is verified, auto merge without UI interactions
  * if the target user's corresponding email claim is NOT verified, **Discussion Item below**
* If `idnetity.oauth_email_signup_conflict_behaviour=merge` and `identity.oauth.providers[].claims.email.auto_merge=false`, then:
  * Show a UI to authenticate with the identity
* If `idnetity.oauth_email_signup_conflict_behaviour=merge_or_new`:
  * Show a UI to tell user he have already signed up an account, does he want to login or create a new account? If Login it will be `=merge`, if new account it will be `=new_account`

I think the above should align with @kiootic and @louischan-oursky discussion mostly? Any differences / suprise?

For the **discussion item*:
If the email claim is not verified, and we do not allow auto_merge, the problem is we will have no choice but violate the configuration to display a UI (it became `auto_merge=false`), or change the conflict_behaviour.

I think we can allow auto-merge without UI interaction in this case, since if `auto_merge=true`, it implies that the developer user trust the email address provided from the provider already, and we have the default = false! So they trust the 3rd parties OAuth Provider to overtake a user account of unverified email sounds fair to me.

**Comment by louischan-oursky** [comment]
From the discussion I had with Terry yesterday, we define the non-interactive merge condition to be:

1. The conflicting identities belong to the same user.
  - Rationale: If there are multiple users, we cannot know which user to merge into it.
2. At least one of the conflicting identities are considered verified.
  - Rationale: Take over account having unverified claim should not be possible. Suppose John signed up with my email `louischan@oursky.com`, he of course cannot verify the email. But I should not be able to take over his account by signing up with Google with `louischan@oursky.com` as well.
3. The new identity is considered verified.
  - Rationale: Take over account with unverified identity should not be possible. Suppose I signup up with my email `louischan@oursky.com` and verified it. Assume A is an untrusted OAuth provider we support. John can use `louischan@oursky.com` to sign up at A first, and then take over my account with signing up with A.

All of these 3 conditions should be true.

If the developer really has strong reason to bypass the last 2 conditions, we may allow them to make condition 2 or 3 true at their will.

For example, the developer can make condition 3 true by specifying `assume_verified` for that OAuth provider. We have this now.

The developer could make condition 2 true if we added `assume_verified` to Login ID. Under the current design, we do not have this yet.

---

> If the email claim is not verified, and we do not allow auto_merge, the problem is we will have no choice but violate the configuration to display a UI (it became auto_merge=false), or change the conflict_behaviour.

I think it is a matter of how to call that configuration. We do not promise we never show a UI. The configuration is about avoid showing UI when we can confidently perform the merge, as opposed to letting the user to choose interactively.

**Comment by chpapa** [comment]
> The conflicting identities belong to the same user.
Rationale: If there are multiple users, we cannot know which user to merge into it.

How could this happen? The only login ID to match is email and it is unique? Or it could be non-unique?

I don't think we have to cover merging of two OAuth Providers, eg FB login merge with Google login.

Well if we want to allow merging of multiple OAuth provider with the same email claims, we better put it as another option

> I think it is a matter of how to call that configuration. We do not promise we never show a UI. The configuration is about avoid showing UI when we can confidently perform the merge, as opposed to letting the user to choose interactively.

But I think it will be a business requirement, either always show a UI or never show a UI. We can't only have an option that some time show, sometime not show the UI for merging, yet we want to keep the configuration simple and not too difficult to understand.

The flow you mentioned consider all edge cases and security considerations, but that probably could be simplify if we take out some assumptions (like merge two OAuth accounts and unverified account can't be takenover)

**Comment by louischan-oursky** [comment]
> How could this happen? The only login ID to match is email and it is unique? Or it could be non-unique?

This happens when the developer set the config to `new_account`, or the user choose to create a new account instead :)
So the configuration really has implication, the same email could be shared by multiple distinct users. This may surprise the developer.

---

> I don't think we have to cover merging of two OAuth Providers, eg FB login merge with Google login.

Why not? It is typical to see an application supporting Google Login and Facebook Login at the same time. If the user forgot that they used to use Google before and use Facebook Login, we should prompt them if they want to login or want to create a new account instead. Adding another option would complicate the configuration and does not bring better UX, it also surprise the developer.

---

> But I think it will be a business requirement, either always show a UI or never show a UI. We can't only have an option that some time show, sometime not show the UI for merging, yet we want to keep the configuration simple and not too difficult to understand.

Actually we can have 3 modes.

1. Always non-interactive. If interactivity is required, show an error instead.
2. Try non-interactive and then interactive. The best of both world.
3. Always interactive. Respect the choice of the user.

---

> The flow you mentioned consider all edge cases and security considerations, but that probably could be simplify if we take out some assumptions (like merge two OAuth accounts and unverified account can't be takenover)

Any particular reason to remove the assumptions? The merge conditions are now well-defined with justifications. I also proposed that the developer can "bypass" some of conditions if they tell us explicitly to do so.

**Comment by chpapa** [comment]
> Actually we can have 3 modes.
>
>    Always non-interactive. If interactivity is required, show an error instead.
>    Try non-interactive and then interactive. The best of both world.
>    Always interactive. Respect the choice of the user.

@louischan-oursky can you write your configuration samples, and also how each configuration would behave finally under what conditions? That will help us to understand the final experience much better then the "internal design description" above.

**Comment by louischan-oursky** [comment]
# 1. Background

The following is the configuration we have currently for specify identity conflict.

As you can see the configuration only covers promotion.
So if the authentication is not a promotion, the current behavior is simply showing an error to the user.

```yaml
identity:
  on_conflict:
    # Valid values are "error" or "login".
    # The default is "error".
    promotion: "error"
```

# 2. Proposed solution

## 2.1. New configuration

```yaml
identity:
  on_conflict:
    # Valid values are ["interactive"], ["noninteractive"] or ["noninteractive", "interactive"]
    # i.e. the valid values are always an array.
    # Note that ["interactive", "noninteractive"] is illegal.
    # Array is used here to indicate the order of the items in the array is the same as the order of the actions we perform.
    # Therefore, ["noninteractive", "interactive"] means perform "noninteractive" first.
    # If "noninteractive" fails, try "interactive" then.
    allowed_modes: ["interactive"]

    noninteractive:
      # Valid values are "error", "create_new_user", "merge_if_possible"
      # If it is "create_new_user", create a new user to resolve the conflict.
      # If it is "merge_if_possible", try to merge the new identity into an existing user. The conditions are explained below.
      # The default is "merge_if_possible".
      policy: "error"

   interactive:
      # The valid values are "merge" and "create_new_user".
      # The order does not matter here.
      # The default value is ["merge"].
      # The value must be an non-empty array.
      allowed_actions: ["merge"]
```

## 2.2. noninteractive.policy == "error"

This is simple to understand.
Just show an error to tell the user there is a conflict.
The authentication is effectively aborted.

What the user can do at this point is to press back button and use another identity.

This is also how we behave at the moment.

## 2.3. noninteractive.policy == "create_new_user"

Resolve the conflict by creating a new user.
The new user owns the new identity.
**This implies two users are now sharing the same email.**

## 2.4. noninteractive.policy == "merge_if_possible"

If all of the following conditions hold,, noninteractive merge is possible.

1. The conflicting identities belong to the same user.
  - Rationale: If there are multiple users, we cannot know which user to merge into it.

2. At least one of the conflicting identities are considered verified.
  - Rationale: Take over account having unverified claim should not be possible. Suppose John signed up with my email `louischan@oursky.com`, he of course cannot verify the email. But I should not be able to take over his account by signing up with Google with `louischan@oursky.com` as well.

3. The new identity is considered verified.
  - Rationale: Take over account with unverified identity should not be possible. Suppose I signup up with my email `louischan@oursky.com` and verified it. Assume A is an untrusted OAuth provider we support. John can use `louischan@oursky.com` to sign up at A first, and then take over my account with signing up with A.

## 2.5. interactive.allowed_actions has "merge"

The user will be shown a list of conflicting identities to authenticate with.
The user should choose one of the identity to authenticate with to proceed.

The overall effect of such action is authentication with the selected identity, followed by add identity operation with the new identity.
This is also how we are going to implement this.

Note that interactive merge does not involve verification at all.
The reason is that we authenticate the user before we add the new identity.

## 2.6. interactive.allowed_actions has "create_user_user"

The user will be shown a button to sign up as a new user.

The overall effect of such action is sign up with the new identity.

**This implies two users are now sharing the same email.**

## 2.7. Example of interactive UI

```
You are authenticating as louischan@oursky.com but
we have found the following identities having the same email.

Please select what you want to do

----------------------------------------

Sign in with Google

----------------------------------------

Sign in with Facebook

----------------------------------------

Sign up as a new user instead

  This means you will be sharing the same email with another user! Make sure you want this.

```

# 3. Recipes

## 3.1. I want my app to be secure, correct, and without surprise

The developer should just leave the configuration as default.

With default configuration, no merge happens without user consent.
No user will share the same email.

```yaml
verification:
  claims:
    email:
      enabled: true
      required: true
identity:
  on_conflict:
    allowed_modes: ["interactive"]
    interactive:
      allowed_actions: ["merge"]
```

## 3.2. I allow my users to login with email, but I do not enforce email verification. I do not want the user to choose anything

The developer should enable noninteractive only.

```yaml
verification:
  claims:
    email:
      enabled: true
      required: false
identity:
  oauth:
    providers:
    - alias: google
      type: google
      claims:
        email:
          assume_verified: true
  on_conflict:
    allowed_modes: ["noninteractive"]
    noninteractive:
      policy: "merge_if_possible"
```

Suppose there is a **verified** email login ID `louischan@oursky.com`, if a user logs in with Google account `louischan@oursky.com`, the new Google OAuth identity is merged into the existing user.

Suppose there is a **unverified** email login ID `user@oursky.com`, if a user logs in with Google account `user@oursky.com`, merge is not possible due to condition 2.

Suppose there is a **verified** Google identity `louischan@oursky.com`, if a user signs up with email login ID `louischan@oursky.com`, merge is not possible due to condition 3. A new email login ID is never considered as verified.

## 3.3. I want to allow the same email shared by different users. But I do not want to enforce this. I want to leave this to the user to choose.

The developer use the following configuration.


```yaml
verification:
  claims:
    email:
      enabled: true
      required: true
identity:
  oauth:
    providers:
    - alias: google
      type: google
      claims:
        email:
          assume_verified: true
  on_conflict:
    allowed_modes: ["interactive"]
    interactive:
      allowed_actions: ["merge", "create_new_user"]
```

## 3.4. I am crazy and I want to allow account take over to happen

This is unsupported yet.
If we really want to support this, we can support `assume_verified: true` for login ID identity as well.

Here is a imaginary configuration illustrating the idea.

```yaml
verification:
  claims:
    email:
      enabled: true
      required: false
identity:
  login_id:
    keys:
    - type: email
      assume_verified: true
  oauth:
    providers:
    - alias: google
      type: google
      claims:
        email:
          assume_verified: true
  on_conflict:
    allowed_modes: ["noninteractive"]
    noninteractive:
      policy: "merge_if_possible"
```

In this setup, signing up with a new login ID can take over an account with Google identity.
Logging in with Google identity can also take over an account with email login ID.

## 3.5. I want to avoid user interaction whenever possible

The developer should set `allowed_modes` to `["noninteractive", "interactive"]`.

```yaml
verification:
  claims:
    email:
      enabled: true
      required: true
identity:
  on_conflict:
    allowed_modes: ["noninteractive", "interactive"]
    noninteractive:
      policy: "merge_if_possible"
    interactive:
      allowed_actions: ["merge"]
```

**Comment by chpapa** [comment]
Thanks @louischan-oursky 

Okay, I try to, based on your suggestion, simplify it to the following, and we can also easier to build the management portal UI based on it, do you think it make sense / easier to understand?

I want to avoid using 3 different attributes + a new `assumed_verified` attribute to have a combination of different behaviour, which is super difficult to explain even with documents, and introduce complexity when we need to build a UI that people can actually understand and configurate...

Simplify to the `on_conflict`, and `interactive_choices` (which only useful when `identity.on_conflict=` `interactive` or `interactive_if_merge_failed`)

```yaml
identity:
  # possible values: error, create_new_user, interactive, interactive_if_merge_failed, merge, merge_insecure 
  on_conflict: interactive
  interactive_choices: ["merge", "create_new_user"]
```

1. error: noninteractive.policy="error"
2. create_new_user: noninteractive.policy="create_new_user"
3. interactive, interactive_choices["merge"]: 3.1
4. interactive, interactive_choices["merge", "create_new_user"]: 3.3
5. interactive, interactive_choices["create_new_user"]: Warn users account exists, do he want to login again, or create a new user?
6. merge: 3.2 - the "secure" merge
7. merge_insecure: 3.4 - merge even if "At least one of the conflicting identities are considered verified" are not met, but new identity still have to be verified!
8. interactive_if_merge_failed: 3.5

Also,
* if `verification.claims.email.enabled=false`, 6/7/8 will ignore the requirement of "At least one of the conflicting identities are considered verified" and "The new identity is considered verified"
