### ISSUE TITLE
Support configuring verified claims per OAuth provider

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#297]
e.g.
```yaml
identity:
  oauth:
    providers:
    - alias: google
      type: google
      client_id: "the_client_id"
      claims:
        email:
          assume_verified: true # Indicates whether the claim is trusted (i.e. verified)
```

ref #198
