### ISSUE TITLE
[Portal] Login ID is ordered.

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#305]
Ideally we should update the UI to convey this. For now, let's follow this order `email`, `phone` and `username`. That is, if `email` is enabled, it is always the first one.

**Comment by keithtkl** [comment]
@louischan-oursky is it for the ordering on the add identify dropdown on `authgear-fluent-user-details-connectedidentities`?

**Comment by louischan-oursky** [comment]
No. I am referring to `authgear-fluent-Authentication-LoginID`.

The corresponding part in the configuration file is

```yaml
identity:
  login_id:
    keys:
      - type: email
      - type: username
      - type: phone
    types:
      email: {}
```

As you can see `identity.login_id.keys` is a list. The order is important in the UI. We by default show the first one as the option for sign up. For example, if the first one is `email`, when you visit `/signup`, it is signing up with `email`.
