### ISSUE TITLE
Forgot password auth flow via phone or email

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3460]
## Problem

A client (codename: Cardinal) requires forgot password via Phone or Email.
Can we achieve that using AuthUI with the latest authflow?

Every existing users in their project have
- username or email or both
- Phone number

## Expected outcome

**New Signup**
- Email + PW

**Login**
- Username/Email & Password

**Forgot & Reset password**

If user enters a **username** in the first step in the login flow:
- The reset mechanism will be SMS link by default. It will ask for phone number when they choose "Forgot Password"
- User enters a phone number
  - If the phone number matches the registered number, an SMS is sent
  - The UI will not tell the user whether the number entered is correct.
  - User click the link in the SMS, reset their pw, go back to the app and login with the new pw.
- User can choose to "reset by email" instead.
  - User is required to have had their email entered
  - A email link is sent if the email match with the system's
  - If the email does not match, or the user doesn't have a email address registered, the email is not sent from the system. The UI will not show a different message.

If user enters a **email** in the first step in the login flow:
- The reset mechanism will be email link be default
- The UI will be prefilled with the email entered by the user in step 1. User sees the email address and press next.
  - A email link is sent and the user can reset pw with it.
- User can choose to "reset by phone number" instead.
  - User is required to enter their phone number.
  - If the phone number matches the registered number, an SMS is sent
  - The UI will not tell the user whether the number entered is correct, or if the user has a phone number registered.

**Comment by tung2744** [comment]
1. Login with username, forgot password with phone number:


https://github.com/authgear/authgear-server/assets/34942210/b1497f48-9e43-4402-a4cd-c0e69638abfc

2. Login with email, Default forgot password with email, but you can change to use phone:

https://github.com/authgear/authgear-server/assets/34942210/3dd5193e-6403-4e02-8ae1-16ba5b26abe0



3. Login with phone. Default forgot password with phone, but you can change to use email.

https://github.com/authgear/authgear-server/assets/34942210/4372f858-948a-49c9-a3e7-b122316b169b

@fungc-io Please see these video for the new ui.

**Comment by limouren** [comment]
It looks good. What would be the configuration looks like for this behaviour?

**Comment by tung2744** [comment]
@limouren 

1. You need to allow using username / email / phone as login id. This step can be done in portal.

```
identity:
  login_id:
    keys:
    - key: phone
      max_length: 40
      modify_disabled: false
      type: phone
    - key: username
      max_length: 40
      modify_disabled: false
      type: username
    - key: email
      max_length: 320
      modify_disabled: false
      type: email
```

2. You need to enable authflow

```
ui:
  implementation: authflow
```

3. In case of login with username, if you want the default login id type for forgot password is phone, you need to override the default account recovery flow in config:

```yaml
authentication_flow:
  account_recovery_flows:
    - name: default
      steps:
      - type: identify
        one_of:
        - identification: phone # <- phone first
          on_failure: ignore
          steps:
            - type: select_destination
              allowed_channels:
                - channel: sms
                  otp_form: code
        - identification: email
          on_failure: ignore
          steps:
            - type: select_destination
              allowed_channels:
                - channel: email
                  otp_form: code
      - type: verify_account_recovery_code
      - type: reset_password
```

Note that this is not on production yet, but you can try it in staging. Currently you cannot adjust the authflow configs in portal. Let me know if you need to update config of any project.
