### ISSUE TITLE
Support reset password by sms otp

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3500]
## Problem

In account recovery, a long code in the link is now supported, the user will click into the long link and open a reset password page. 
However while the long link is suitable for email, it's not suitable for SMS, because

- The long string of the link is printed as plain text in the SMS, this make it looks like spam, and may exceed the SMS length limit.
- In some countries such as Taiwan, as spam prevention method, the domain of a link inside a SMS must be first registered with the governing body.

Therefore, OTP is usually used in SMS for resetting password instead.

**Changes needed**

- Support using OTP to authenticate the user and commit a reset password request.
- Support sending this OTP with Email and SMS.
- Because OTP is much shorter than the long code, the valid time should be smaller than which the long code has.

### Forgot password configs

Original:

```yaml
forgot_password:
  code_valid_period: 1200s
```

New:

```yaml
forgot_password:
  valid_period:
    link: 1200s
    code: 300s
ui:
  forgot_password:
    phone: 
      - channel: sms 
        otp_form: code
    email: 
      - channel: email 
        otp_form: link
```

1. Deprecate `forgot_password.code_valid_period`, replace with `forgot_password.link_valid_period` which is clearer that it must be used as a link.
2. Add `forgot_password.otp_valid_period`. By default it should be `300s`.

### Authflow config changes

```yaml
account_recovery_flows:
- name: default
  steps:
    - type: identify
      one_of:
      - identification: email
        on_failure: ignore
      - identification: phone
        on_failure: ignore
    - type: select_destination
      enumerate_destinations: false
      # New field for select_destination
      # 1. If not provided, all options are allowed
      #    But if enumerate_destinations is false, only related options will appear
      # 2. If provided, only specified options are allowed in this step, and order is preserved
      allowed_channels:
        - channel: sms
          otp_form: link
        - channel: sms
          otp_form: code
        - channel: whatsapp
          otp_form: code
        - channel: sms
          otp_form: code
    - type: verify_account_recovery_code
    - type: reset_password
```

`allowed_options` of the generated flow will be controlled by the `forgot_password.channel` config.

## Authflow api changes

1. In step `select_destination`, if the previous identify method is a phone number, one more option will be returned as destination.

```jsonc
// Request for step `identify`
{
  "state_token": "authflowstate_8GDMH1QCJ9WCTXXFB270ZPVE8R6QXZSY",
  "batch_input": [
    {
      "identification": "phone",
      "login_id": "+85267676767"
    }
  ]
}

// Response, which next step is `select_destination`
{
  "result": {
    "state_token": "authflowstate_X4V0XMBM71B2967FT6TP8MCZP6MJYKZ3",
    "type": "account_recovery",
    "name": "default",
    "action": {
      "type": "select_destination",
      "data": {
        "options": [
          {
            "masked_display_name": "+8526767****",
            "channel": "sms",
            "otp_form": "link" // This field is added
          },
          {
            "masked_display_name": "+8526767****",
            "channel": "sms",
            "otp_form": "code" // This field is added
          }
        ]
      }
    }
  }
}

```

2. In step `verify_account_recovery_code`, information about the previously selected destination will be added to data.

```jsonc
// Response if next step is verify_account_recovery_code
{
  "result": {
    "state_token": "authflowstate_JD7YJA2XDPMDM7HXN7HFRN0450M4BRA5",
    "type": "account_recovery",
    "name": "default",
    "action": {
      "type": "verify_account_recovery_code",
      "data": {
        "masked_display_name": "+8526767****",
        "channel": "sms",
        "otp_form": "code",
        // ...resend otp related data
      }
    }
  }
}
``` 

The remaining flow remain the same.

## Auth UI changes

1. During forgot password, if the input is a phone number, by default the auth ui always select the otp option if available at `select_destination`.
2. Then, in the next step, it should show an otp input screen if the selected destination is having `kind=otp`, else, display the original screen.
3. The otp input screen will go to reset password screen directly.

## Portal Changes

![Image](https://github.com/authgear/authgear-server/assets/34942210/1685a5dc-f91e-4231-af0d-a24b745ff1d5)

- Add a field here "Reset otp valid duration (seconds)". By default 300s.
- Rename the original field to "Reset link valid duration (seconds)"

Add the following fields to control the behavoir of the default (generated) auth flow:

- Reset password with email by [DROPDOWN(link/code)] (show this if email is enabled)
- Reset password with phone by [DROPDOWN(sms/whatsapp)] (show this if phone is enabled)
  - [DROPDOWN(link/code)] : sms only

![Image](https://github.com/authgear/authgear-server/assets/34942210/dda01188-3441-411d-9906-52c676966c2a)

Allow modifying reset password by otp template.

- Change the current "Reset Password" tab to "Reset Password by Link".

- Add a new tab "Reset Password by OTP".

## Implementation

- #3501 
- #3502 
- #3503 
- #3504

**Comment by fungc-io** [comment]
The UI change lgtm,
i've add the context to the issue body.

We could build support for "resetting pw by OTP via Email" too after we did this feature. But this is lower priority.

**Comment by louischan-oursky** [comment]
I would like to keep the existing behavior by default. That is, the new behavior is opt-in.

1. I agree we should deprecate `code_valid_period` as it now becomes ambiguous. `link_valid_period` should be a pointer in the implementation. If `code_valid_period` is specified and `link_valid_period` is unspecified, then `link_valid_period` takes the value of `code_valid_period`. This ensures configured `code_valid_period` continues to work.
2. To keep the existing behavior, we need to add an option to control which login ID uses which method. Authui only uses the first method. The order is important, and is preserved in the flow response. This allows the developer to use whatever method they want.

```
forgot_password:
  link_valid_period: 1200s
  otp_valid_period: 300s
  # Both email_methods and phone_methods are [link, otp] by default, to preserve existing behavior.
  email_methods:
  - link
  - otp
 phone_methods:
  - link
  - otp
```

3. On portal, we will add a toggle to change `phone_methods: [link, otp]` to `phone_methods: [otp, link]`.

**Comment by tung2744** [comment]
@louischan-oursky 

1. Agree.

2. Agree. But I suggest a format which matches the naming in authflow api better.

```yaml
forgot_password:
  link_valid_period: 1200s
  otp_valid_period: 300s
  channels:
    sms:
        kinds:
        - otp
        - link
    email:
         kinds:
         - link
         - otp
```

3. Do you mean there will be two toggles?
    - Enable reset by sms otp: Allow setting otp_valid_period
    - Use sms otp in auth ui: Define the order

**Comment by louischan-oursky** [comment]
The problem is we now have a set of options to control the generated flow (and hence the behavior of authui). And our authflow implementation reads the same set of options in some case, for example `phone_otp_mode` and `email_otp_mode`. If we want to authflow to be entirely customizable, then authflow should not read any existing configuration. This implies the options we add purely affect the generated flow (and the behavior of authui).

So

1. Make sure authflow should only read the flow configuration, no other configurations.
2. If we do not plan to allow switching between link and otp in forgot password, then we need not introduce a list in the options. (But being a list allows us to support switching easily in the future, just in case)

Regarding the portal

```
- Reset password with email by [DROPDOWN] (show this if email is enabled)
- Reset password with phone by [DROPDOWN] (show this if phone is enabled)
- Reset link valid duration
- Reset OTP valid duration
```

**Comment by tung2744** [comment]
I've updated the issue according to our latest comments.

**Comment by tung2744** [comment]
I found I've missed the template configurations in the portal, I updated the issue again for it.

**Comment by chpapa** [comment]
Thanks @tung2744 @louischan-oursky , sorry two late comments:

1. Maybe we should use something other than `kinds` for `otp` and `link`? Not sure I'm right, but I seems to remember I saw `kinds` somewhere else. If that's true, better don't overload the terms for different meaning, unless the usage is very consistent. (So you two know better than me on it...) If the `kinds` here conflict with other usage of `kind`/`kinds`, we can use a more specific name like code type etc?
2. From users perspective, we should use link for email reset by default, and OTP for SMS by default. That's more common.

**Comment by louischan-oursky** [comment]
> From users perspective, we should use link for email reset by default, and OTP for SMS by default. That's more common.

So existing projects keep their current behavior, and new projects have the new defaults. Or do we want to change the defaults for all projects?

**Comment by tung2744** [comment]
> Maybe we should use something other than kinds for otp and link? 

Maybe we can use the word "form".

**Comment by chpapa** [comment]
@tung2744 @louischan-oursky 

## On naming

Do we have other part of config that is also about choosing between SMS and Whatsapp etc? (I think we have it for passwordless login?) Is the name consistent? As long as it is consistent with other usage, and also don't conflict/overload with other usage that's not similar, I think `otp_form` is ok. (Or similar naming like `otp_type` etc)

## On `allowed_destination_types`

`allowed_destination_types`: oh this is confusing to me... sorry I didn't read in details before :(

When I saw `allowed_destination_types`, and `enumerate_destination`, I think it is for picking which phone no or which email to send.

I think we will need to support it eventually.

But if we only focus at choosing which `channel`, since we already use the term `channel` in the config (as follows):

```
      allowed_destination_types:
        - channel: sms
          otp_form: link
        - channel: sms
          otp_form: code
        - channel: whatsapp
          otp_form: code
        - channel: sms
          otp_form: code
```

What about if we use: `enumerate_channels` and `allowed_channels` (or `supported_channels`) instead?

## What is "ui"?

BTW, since I just read the description config line by line, I noticed in the config, what is `ui` meant here?

```
forgot_password:
  valid_period:
    link: 1200s
    code: 300s
ui:
  forgot_password:
    phone: 
      - channel: sms 
        otp_form: code
    email: 
      - channel: email 
        otp_form: link
```

**Comment by tung2744** [comment]
@chpapa 

> Do we have other part of config that is also about choosing between SMS and Whatsapp etc?

Yes there is. It is for choosing where the oob otp code for login / verification can be send to.

```yaml
authenticator:
  oob_otp:
    sms:
      phone_otp_mode: whatsapp_sms (Whatsapp OR SMS) / sms (SMS Ony) / whatsapp (Whatsapp Only)
```

Note that this config usually will not be modify by the user directly. The user should modify it by the portal ui.

> When I saw allowed_destination_types, and enumerate_destination, I think it is for picking which phone no or which email to send.

- `enumerate_destination`
    - It is to allow the user to select other emails / phone number in the same account to receive the account recovery code, even if it is not the one he inputted. If it is true, the api will output other phone / emails (masked) associated with the same account so user can choose between them.
- `allowed_destination_types`
    - It is to define the channel & otp_form allowed to use. For example, if a user is trying to reset password by a phone number, then channel can be one of `whatsapp` or `sms`, and otp_form can be one of `link` or `code`. This field is a list defining what combinations are allowed. The purpose of this field is a bit different with `enumerate_destination` because it will not list out other phone number / emails of the account.

Renaming `allowed_destination_types` to `allowed_channels` is good for me. But I prefer keeping `enumerate_destination` because it is not only enumerating channels, but it tell the exact destination (email / phone number).

 
> What is "ui"?

We are trying to group configs only affecting the default auth ui into the "ui" config.

```yaml
ui:
  forgot_password:
    phone: 
      - channel: sms 
        otp_form: code
    email: 
      - channel: email 
        otp_form: link
```

The above config is telling the default ui:
  - when user inputs a phone in forgot password flow, it will send the 6-digit code to the phone number by sms
  - when user inputs an email in forgot password flow, it will send the link to the email address by email

Note that it doesn't affect the authflow api, i.e. the authflow api is still referring to the authflow api config to determine the allowed options.
