### ISSUE TITLE
Fixed OTP for a given list of phone numbers

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3520]
## Problem

For testing passwordless login using custom auth flow/custom UI, a fixed OTP is needed to be provided to the google/apple store

## Appetite

1 day

## Solution

Given a list of phone number in allowlist set for a certain project, the OTP will always by 000000 for that project.

**Comment by tung2744** [comment]
Proposed config in `authgear.yaml`:

```yaml
test_mode:
    fixed_oob_otp:
        enabled_targets:
            - "+85260000001"
            - "+85260000002"
            - "test@example.com"
```

**Comment by louischan-oursky** [comment]
The fixed OTP should be configurable. Maybe we should support regex as well.

**Comment by tung2744** [comment]
@louischan-oursky However, I think that becomes conflict with the current feature conflict. I think for now we reference the fixed otp configured in feature config first.

**Comment by louischan-oursky** [comment]
1. Change GenerateCode to take target too. If the target matches any rule, then use that rule to generate the code
2. If the target does not match any rule, see if test mode is feature config is enabled. If yes, generate the fixed code
3. Otherwise generate a random code.

```yaml
test_mode:
  oob_otp:
    enabled: true
    rules:
    - type: literal
      value: "+85251000000"
      target_type: phone
      fixed_code: "000000"
    - type: regex
      value: "^\\+8526\\d{7}$"
      target_type: phone
      fixed_code: "000000"
    - type: literal
      value: "user@example.com"
      target_type: email
      fixed_code: "000000"
    - type: regex
      value: "@example.com$"
      target_type: email
      fixed_code: "000000"
```

**Comment by louischan-oursky** [comment]
```yaml
test_mode:
  oob_otp:
    enabled: true
    rules:
    - regex: "^\\+85251000000$"
      fixed_code: "000000"
    - regex: "^\\+8526\\d{7}$"
      fixed_code: "000000"
    - regex: "^user@example.com$"
      fixed_code: "000000"
    - regex: "@example.com$"
      fixed_code: "000000"
```
