### ISSUE TITLE
Specify authflow in when initializing authentication from SDK

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3921]
Let's say the developer defined multiple authflow, they should be able to use them in different scenario.

For example:

* In an staff only app, the users can only use ADFS login
* In app for both staff and external vendor, the users can use either email or ADFS for login.

**Comment by fungc-io** [comment]
@newman please help specify the design along the general direction:

* Allowlist in Application for authflows
* Accept authflow as a parameter in authorize request.
  * If not given, the 1st value in the allowlist is used
  * If given, validate with the allowlist. Pass if exist in allowlist, error if not in it.

**Comment by louischan-oursky** [comment]
- Support `x_authentication_flow_type`, `x_authentication_flow_name` in the authorization endpoint.
- Add `x_allowed_authentication_flows` to `oauth.clients`.

```
x_allowed_authentication_flows:
- type: login
  name: default
- type: signup
  name: default
- type: signup_login
  name: default
```

Behavior

|x_authentication_flow_name|x_allowed_authentication_flows|outcome|
|---|---|---|
|unspecified|unspecified|Leave flow name unspecified. Let Auth UI to choose authflow|
|"flow1"|unspecified|Use flow1|
|unspecified|["flow1"]|Use flow1|
|"flow2"|["flow1"]|Return OAuth Error|
|"flow1"|["flow1"]|Use flow1|

---

But we also need to think about how does this work with the existing `x_page` parameter.

Some options
- `x_page` is mutually exclusive with `x_authentication_flow_type` and `x_authentication_flow_name`. That is, when `x_authentication_flow_type` and `x_authentication_flow_name` are present, `x_page` is ignored.

**Comment by fungc-io** [comment]
Hi @louischan @newman,

Can you help set up a testing project for QA and i to test this feature? perhaps using `qa-ui-vtwo` on staging is a good idea

**Comment by louischan-oursky** [comment]
OK

**Comment by louischan-oursky** [comment]
```yaml
authentication_flow:
  login_flows:
  - name: test1
    steps:
    - name: identify
      one_of:
      - identification: email
        steps:
        - name: authenticate_primary_email
          one_of:
          - authentication: primary_password
          type: authenticate
      type: identify
    - type: check_account_status
  - name: test2
    steps:
    - name: identify
      one_of:
      - identification: phone
        steps:
        - name: authenticate_primary_email
          one_of:
          - authentication: primary_password
          type: authenticate
      type: identify
    - type: check_account_status
ui:
  authentication_flow:
    groups:
    - flows:
      - name: default
        type: signup
      - name: default
        type: promote
      - name: test1
        type: login
      - name: default
        type: signup_login
      - name: default
        type: reauth
      - name: default
        type: account_recovery
      name: test1
    - flows:
      - name: default
        type: signup
      - name: default
        type: promote
      - name: test2
        type: login
      - name: default
        type: signup_login
      - name: default
        type: reauth
      - name: default
        type: account_recovery
      name: test2
oauth:
  clients:
  - access_token_lifetime_seconds: 1800
    client_id: 720d7e48242364bd
    grant_types:
    - authorization_code
    - refresh_token
    name: My App
    post_logout_redirect_uris:
    - http://localhost/after-logout
    redirect_uris:
    - http://localhost/after-authentication
    - https://token-app1.authgear.pandawork.com/auth-redirect
    - https://token-app1.authgear.pandawork.com/reauth-redirect
    - https://token-app1.authgear.pandawork.com/promote-anonymous-user-redirect
    - https://token-app2.authgear.pandawork.com/auth-redirect
    - https://token-app2.authgear.pandawork.com/reauth-redirect
    - https://token-app2.authgear.pandawork.com/promote-anonymous-user-redirect
    refresh_token_idle_timeout_enabled: true
    refresh_token_idle_timeout_seconds: 2592000
    refresh_token_lifetime_seconds: 31449600
    response_types:
    - code
    - none
    x_application_type: spa
    x_authentication_flow_allowlist:
      groups:
      - name: test1
```

- Two custom login flows were defined, namely `test1` and `test2`.
- Two groups were defined, namely `test1` and `test2`.
- The client `720d7e48242364bd` is restricted to use `test1`.
