### ISSUE TITLE
OAuth callback does not handle AuthflowV2

### ISSUE THREAD

**Issue by IniZio** [authgear/authgear-server#3939]
For example with following authgear config

```
authentication_flow:
  login_flows:
  - name: default
    steps:
    - one_of:
      - identification: oauth
        steps:
        - one_of:
          - authentication: primary_oob_otp_sms
          - authentication: primary_oob_otp_email
          type: authenticate
    type: identify

ui:
  implementation: authflowv2
```

After OAuth, user gets redirected to authflowv1 instead of authflowv2

It should be due to `pkg/auth/handler/webapp/sso_callback.go` not handling authflowv2 switch
