### ISSUE TITLE
[e2e testing] Validation error if I use "000000" as fixed code

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#4180]
Add this section to the config:

```
    test_mode:
      oob_otp:
        enabled: true
        rules:
          - fixed_code: "aaaaaa"
            regex: ".*"
```

Got this error

```
    cmd.go:75: 2024/04/29 16:14:47 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
        Error: json: cannot unmarshal number into Go struct field TestModeOOBOTPRule.test_mode.oob_otp.rules.fixed_code of type string
        Usage:
           create-configsource [flags]
        
        Flags:
              --app-id string            App ID (default "")
              --config-override string   Config override (default "")
              --config-source string     Config source (default "")
          -h, --help                     help for create-configsource
        
    testcase.go:61: failed to create config source: exit status 1
```
