### ISSUE TITLE
SSOConfig is not referenced correctly

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#8]

**Comment by louischan-oursky** [comment]
@kiootic I propose we restructure the config like this

```
identity:
  login_id: ...
  oauth:
    providers:
    - type: google
```

The keys under `identity` match the type of supported identity.

Thoughts?
